# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'EncryptFileDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 103)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.tbSelectDir = QtWidgets.QToolButton(Dialog)
        self.tbSelectDir.setObjectName("tbSelectDir")
        self.gridLayout.addWidget(self.tbSelectDir, 1, 2, 1, 1)
        self.tbSelectFiles = QtWidgets.QToolButton(Dialog)
        self.tbSelectFiles.setObjectName("tbSelectFiles")
        self.gridLayout.addWidget(self.tbSelectFiles, 0, 2, 1, 1)
        self.txtInputFile = QtWidgets.QLineEdit(Dialog)
        self.txtInputFile.setReadOnly(True)
        self.txtInputFile.setObjectName("txtInputFile")
        self.gridLayout.addWidget(self.txtInputFile, 0, 1, 1, 1)
        self.txtOutputDir = QtWidgets.QLineEdit(Dialog)
        self.txtOutputDir.setReadOnly(True)
        self.txtOutputDir.setObjectName("txtOutputDir")
        self.gridLayout.addWidget(self.txtOutputDir, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.btnOk = QtWidgets.QPushButton(Dialog)
        self.btnOk.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btnOk.setObjectName("btnOk")
        self.horizontalLayout_2.addWidget(self.btnOk)
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setMaximumSize(QtCore.QSize(80, 16777215))
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_2.addWidget(self.btnCancel)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 3)
        self.horizontalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "图片"))
        self.label_2.setText(_translate("Dialog", "输出目录"))
        self.tbSelectDir.setText(_translate("Dialog", "..."))
        self.tbSelectFiles.setText(_translate("Dialog", "..."))
        self.btnOk.setText(_translate("Dialog", "确定"))
        self.btnCancel.setText(_translate("Dialog", "取消"))
