# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KeyCreateDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 150)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txtName = QtWidgets.QLineEdit(Dialog)
        self.txtName.setObjectName("txtName")
        self.gridLayout.addWidget(self.txtName, 0, 1, 1, 1)
        self.txtPassword2 = QtWidgets.QLineEdit(Dialog)
        self.txtPassword2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword2.setObjectName("txtPassword2")
        self.gridLayout.addWidget(self.txtPassword2, 2, 1, 1, 1)
        self.btnFileChooser = QtWidgets.QPushButton(Dialog)
        self.btnFileChooser.setMinimumSize(QtCore.QSize(30, 0))
        self.btnFileChooser.setMaximumSize(QtCore.QSize(30, 16777215))
        self.btnFileChooser.setObjectName("btnFileChooser")
        self.gridLayout.addWidget(self.btnFileChooser, 3, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.txtPassword1 = QtWidgets.QLineEdit(Dialog)
        self.txtPassword1.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txtPassword1.setObjectName("txtPassword1")
        self.gridLayout.addWidget(self.txtPassword1, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.txtPath = QtWidgets.QLineEdit(Dialog)
        self.txtPath.setObjectName("txtPath")
        self.gridLayout.addWidget(self.txtPath, 3, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnOk = QtWidgets.QPushButton(Dialog)
        self.btnOk.setObjectName("btnOk")
        self.horizontalLayout.addWidget(self.btnOk)
        self.btnCancel = QtWidgets.QPushButton(Dialog)
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout.addWidget(self.btnCancel)
        self.gridLayout.addLayout(self.horizontalLayout, 4, 0, 1, 3)
        self.verticalLayout.addLayout(self.gridLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.txtName, self.txtPassword1)
        Dialog.setTabOrder(self.txtPassword1, self.txtPassword2)
        Dialog.setTabOrder(self.txtPassword2, self.txtPath)
        Dialog.setTabOrder(self.txtPath, self.btnFileChooser)
        Dialog.setTabOrder(self.btnFileChooser, self.btnOk)
        Dialog.setTabOrder(self.btnOk, self.btnCancel)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "密码1"))
        self.label.setText(_translate("Dialog", "名称"))
        self.btnFileChooser.setText(_translate("Dialog", "..."))
        self.label_4.setText(_translate("Dialog", "密码2"))
        self.label_2.setText(_translate("Dialog", "路径"))
        self.btnOk.setText(_translate("Dialog", "保存"))
        self.btnCancel.setText(_translate("Dialog", "取消"))
