# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KeyMgrDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(524, 356)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 25))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tbCreate = QtWidgets.QToolButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tbCreate.sizePolicy().hasHeightForWidth())
        self.tbCreate.setSizePolicy(sizePolicy)
        self.tbCreate.setMinimumSize(QtCore.QSize(50, 25))
        self.tbCreate.setObjectName("tbCreate")
        self.horizontalLayout.addWidget(self.tbCreate)
        self.tbAdd = QtWidgets.QToolButton(self.widget)
        self.tbAdd.setMinimumSize(QtCore.QSize(50, 25))
        self.tbAdd.setObjectName("tbAdd")
        self.horizontalLayout.addWidget(self.tbAdd)
        self.tbRemove = QtWidgets.QToolButton(self.widget)
        self.tbRemove.setMinimumSize(QtCore.QSize(50, 25))
        self.tbRemove.setObjectName("tbRemove")
        self.horizontalLayout.addWidget(self.tbRemove)
        self.verticalLayout.addWidget(self.widget, 0, QtCore.Qt.AlignLeft)
        self.keyListView = QtWidgets.QListView(Dialog)
        self.keyListView.setObjectName("keyListView")
        self.verticalLayout.addWidget(self.keyListView)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept)
        self.buttonBox.rejected.connect(Dialog.reject)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.tbCreate.setText(_translate("Dialog", "新建"))
        self.tbAdd.setText(_translate("Dialog", "添加"))
        self.tbRemove.setText(_translate("Dialog", "删除"))
